disabled = false
languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 1
title = "NizerossのBlog"

[params]
  displayName = "简体中文"
  isoCode = "cn"
  rtl = false
  dateFormat = "2006 年 1 月 2 日"
  logo = "img/site_logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "NIZEROSS's website"
  copyright = '© 2025 - { year } Nizeross All Rights Reserved.'

[params.author]
  name = "NIZEROSS"
  image = "img/avatar.png"
  headline = "驕る鳥は墜ち 頭垂れて乞い"
  bio = "Everyone is mania in general"
  links = [
    { bilibili = "https://space.bilibili.com/176505165" },
    { email = "mailto:1578686349@qq.com" },
    { steam = "https://steamcommunity.com/id/nizeross/" },
   ]